config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users do
    post 'toggle_activity', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get '/', to: 'breweries#index'

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage
  extend Top

  has_secure_password

  validates :username, uniqueness: true,
            length: { minimum: 3, maximum: 15}
  validates :password, length: {minimum: 4}
  validate :password_must_contain_digit_and_caps

  has_many :ratings, dependent: :destroy   # käyttäjällä on monta ratingia
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  def self.active_raters
    User.all.sort_by{|user| -user.ratings.count}
  end

  def password_must_contain_digit_and_caps
    contains_digit = !password.match(/[\d{1,}]+/).nil? if not password.nil?
    contains_capital_letter = !password.match(/[A-Z]+/).nil? if not password.nil?
    if not contains_digit or not contains_capital_letter
      errors.add(:password, "Password must contain a capital letter and a number")
    end
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_brewery
    favorite :brewery
  end

  def favorite_style
    favorite :style
  end

  def average_ratings(hash)
    hash.keys.each do |key|
      sum = hash[key].inject(0.0) { |sum, rating| sum + rating.score }
      hash[key] = sum / hash[key].count
    end
    return hash
  end

  def rated(category)
    ratings.map{ |r| r.beer.send(category) }.uniq
  end

  def rating_of(category, item)
    ratings_of_item = ratings.select do |r|
      r.beer.send(category) == item
    end
    ratings_of_item.map(&:score).sum / ratings_of_item.count
  end

  def favorite(category)
    return nil if ratings.empty?

    category_ratings = rated(category).inject([]) do |set, item|
      set << {
          item: item,
          rating: rating_of(category, item) }
    end

    category_ratings.sort_by { |item| item[:rating] }.last[:item]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    user = User.find(params[:id])
    user.update_attribute :active, (not user.active)

    new_status = user.active? ? "active" : "frozen"

    redirect_to :back, notice:"User account status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
      <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username %>
      </div>
  <% end %>

  <div class="field">
    <% if @user.new_record? %>
        <%= f.label :password %>
        <br/>
    <% else %>
        <%= f.label :new_password %>
        <br/>
    <% end %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= current_user.username %></h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <% if not user.active and current_user and current_user.admin %>
            <td><span class="label label-info">account frozen</span></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>
  <%= @user.username %>
  <% if not @user.active and current_user.admin %>
      <td><span class="label label-info">account frozen</span></td>
  <% end %>
</h1>

<% if @user.ratings.empty? %>
  <p>No ratings</p>
<% else %>
  <p>Has <%= pluralize(@user.ratings.count, "rating") %>, average <%= round @user.average_rating %></p>

  <p>
    Favorite style: <%= @user.favorite_style %>
    <br>
    Favorite brewery: <%= @user.favorite_brewery.name %>
    <br>
  </p>

  <h2>Ratings</h2>
    <ul>
      <% @user.ratings.each do |rating| %>
          <li>
            <%= rating %>
            <% if @user == current_user %>
                <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </li>
      <% end %>
    </ul>

<%end%>

<h2>BeerClub Memberships</h2>
<% if not @user.memberships.empty? %>
    <ul>
      <% @user.memberships.each do |membership| %>
          <li><%= link_to membership.beer_club.name, membership.beer_club %></li>
      <% end %>
    </ul>
<% else %>
    <p>No club memberships</p>
<% end %>

<br>
<% if @user == current_user %>
    <%= edit_and_destroy_buttons(@user) %>
<% end %>
<br><br>
<% if current_user and current_user.admin and current_user != @user %>
    <% if @user.active %>
        <%= link_to "Freeze account", toggle_activity_user_path(@user.id), method: :post, class: "btn btn-danger" %>
    <%else%>
        <%= link_to "Reactivate account", toggle_activity_user_path(@user.id), method: :post, class: "btn btn-danger" %>
    <%end%>
<%end%>