config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users do
    post 'toggle_activity', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get '/', to: 'breweries#index'

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers,  dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :name, length: {minimum: 1}
  validates :year, presence: true
  validates :year, numericality: {greater_than_or_equal_to: 1042,
                                  only_integer: true}
  validate :year_cant_be_in_the_future

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  include RatingAverage
  extend Top

  def year_cant_be_in_the_future
    if not year.nil? and year > Date.today.year
      errors.add(:year, "can't be in the future.")
    end
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2015
    puts "changed year to #{year}"
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list, :nglist]


  # GET /breweries
  # GET /breweries.json
  def index
    order = params[:order] || 'name'
    case order
      when 'name' then
        @active_breweries = Brewery.active.order(:name)
        @retired_breweries = Brewery.retired.order(:name)
      when 'year' then
        @active_breweries = Brewery.active.order(:year)
        @retired_breweries = Brewery.retired.order(:year)
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  def list
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"Brewery activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    private

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th><%= link_to 'Name', breweries_path(order:"name"), class:'btn btn-default' %></th>
    <th><%= link_to 'Year', breweries_path(order:"year"), class:'btn btn-default' %></th>
  </tr>
  </thead>
  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><td><%= link_to('Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger') if current_user %></td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breweries</h1>

<% cache "brewerylist-#{@order}", skip_digest: true do %>
    <h2>Active</h2>
    <p> Number of active breweries: <%= @active_breweries.count %> </p>
    <%= render 'list', breweries: @active_breweries %>
    <h2>Retired</h2>
    <p> Number of retired breweries: <%= @retired_breweries.count %> </p>
    <%= render 'list', breweries: @retired_breweries %>
<% end %>
<br>
<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary" %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

app/views/breweries/panimot.html.erb
 panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<h2>
  <%= @brewery.name %>
  <% if not @brewery.active  %>
      <span class="label label-info">retired</span>
  <% end %>
</h2>

<i><p>
  Established in
  <%= @brewery.year %>.
</i></p>

<br>
<p>
  Number of beers
  <%= @brewery.beers.count %>
</p>

<p>
  <% @brewery.beers.each do |beer| %>
    <%= link_to beer.name, beer %>
  <% end %>
</p>

<br>
<p>
  <% if @brewery.ratings.empty? %>
    Brewery has not yet been rated!
<% else %>
    Brewery has <%= pluralize(@brewery.ratings.count, 'rating') %>. Average: <%= round @brewery.average_rating %>
<% end %>
</p>

<br>
<% if current_user %>
    <% if @brewery.active %>
        <%= link_to "Change activity to retired", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
    <%else%>
        <%= link_to "Activate brewery", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
    <%end%>
<% end %>

<br><br>
<%= edit_and_destroy_buttons(@brewery) %>